# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e33413ce450a1397dc5c1fbbbe6862cba1bf0c188248dcd4268d2f6b89bf06b429b466638db68aa1a5e702f811270e4eaa66a9180bdfd531f33587bb869ee5

test:
  secret_key_base: 19c45476bd39a1ab0eb3c0d92c543591592185c25145a087908ede8c589cad5883f1cc6c4208ec6b1ad3ad10edea68cd5a08192a9b873b16ceed6f40a0ee58fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
